CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  service VARCHAR(255) DEFAULT 'mine' NOT NULL,
  role VARCHAR(255) DEFAULT 'user' NOT NULL
);
